version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
          - run:
          name: Install AWS CLI
          command: |
                 apk --no-cache add py-pip
                  pip install awscli
            - run: npm install
            - run:
                name: Rebuild node-sass
                command: npm rebuild node-sass
            - run:
               name: Building HTML
               command: npm run build
workflows:
    build-and-test:
      jobs:
        - build-and-test